name: Pokémon Card Scraper

on:
  schedule:
    - cron: '0 12 * * 1-5'  # Runs at 12PM UTC, Mon-Fri
  workflow_dispatch:         # Allow manual runs

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build Docker image
        run: docker build -t scraper .
      - name: Run scraper
        run: |
          mkdir -p ./output
          docker run \
            --shm-size=2g \
            -v "$(pwd)/output:/app/output" \
            scraper
      - name: Upload results
        uses: actions/upload-artifact@v3
        with:
          name: pokemon-cards
          path: output/*.csv
